# Generated by Django 6.0.4 on 2026-05-05 02:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AmenityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#3388ff", max_length=7)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_types",
                        to="maps.amenitytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Amenity Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("prop_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("operator", models.CharField(blank=True, max_length=200)),
                ("hours_of_operation", models.JSONField(blank=True, default=dict)),
                ("is_open_24hrs", models.BooleanField(default=False)),
                ("monday_open", models.TimeField(blank=True, null=True)),
                ("monday_close", models.TimeField(blank=True, null=True)),
                ("tuesday_open", models.TimeField(blank=True, null=True)),
                ("tuesday_close", models.TimeField(blank=True, null=True)),
                ("wednesday_open", models.TimeField(blank=True, null=True)),
                ("wednesday_close", models.TimeField(blank=True, null=True)),
                ("thursday_open", models.TimeField(blank=True, null=True)),
                ("thursday_close", models.TimeField(blank=True, null=True)),
                ("friday_open", models.TimeField(blank=True, null=True)),
                ("friday_close", models.TimeField(blank=True, null=True)),
                ("saturday_open", models.TimeField(blank=True, null=True)),
                ("saturday_close", models.TimeField(blank=True, null=True)),
                ("sunday_open", models.TimeField(blank=True, null=True)),
                ("sunday_close", models.TimeField(blank=True, null=True)),
                ("changing_stations", models.BooleanField(default=False)),
                (
                    "accessibility",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Unknown"),
                            ("Not Accessible", "Not Accessible"),
                            ("Limited Accessibility", "Limited Accessibility"),
                            ("Partially Accessible", "Partially Accessible"),
                            ("Fully Accessible", "Fully Accessible"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("seasonal", models.BooleanField(default=False)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="maps.amenitytype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("session_key", models.CharField(blank=True, max_length=64)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_reports",
                        to="maps.amenity",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Message"),
                            ("group", "Group Chat"),
                            ("amenity_forum", "Amenity Forum"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Custom name for group and forum chats",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        blank=True,
                        help_text="For amenity forum chats, reference the amenity being discussed",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="maps.amenity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="maps.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_on_updates", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="maps.amenity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="maps.chat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        help_text="Rating from 1 to 5 stars",
                    ),
                ),
                ("review_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="maps.amenity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AmenityPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="amenity_photos/%Y/%m/%d/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="maps.amenity",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="maps.review",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="maps.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(fields=["active"], name="maps_amenit_active_1b0ff3_idx"),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["amenity_type", "active"], name="maps_amenit_amenity_e0f3c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["is_open_24hrs"], name="maps_amenit_is_open_494122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["monday_open", "monday_close"],
                name="maps_amenit_monday__21e969_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["tuesday_open", "tuesday_close"],
                name="maps_amenit_tuesday_afd7d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["wednesday_open", "wednesday_close"],
                name="maps_amenit_wednesd_20bdfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["thursday_open", "thursday_close"],
                name="maps_amenit_thursda_bcc3a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["friday_open", "friday_close"],
                name="maps_amenit_friday__7d25a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["saturday_open", "saturday_close"],
                name="maps_amenit_saturda_078037_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["sunday_open", "sunday_close"],
                name="maps_amenit_sunday__e0c0f9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="amenity",
            unique_together={("amenity_type", "external_id")},
        ),
        migrations.AddIndex(
            model_name="availabilityreport",
            index=models.Index(
                fields=["amenity", "reported_at"], name="avail_amenity_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityreport",
            index=models.Index(
                fields=["session_key", "reported_at"], name="avail_session_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["-last_message_at"], name="maps_chat_last_me_aff608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["chat_type", "-last_message_at"],
                name="maps_chat_chat_ty_456d1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["user", "-joined_at"], name="maps_chatpa_user_id_e99913_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("chat", "user")},
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["user", "-created_at"], name="fav_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(fields=["amenity", "user"], name="fav_amenity_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "amenity")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "-created_at"], name="maps_messag_chat_id_5b3ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-created_at"], name="maps_messag_sender__e56bbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["amenity", "-created_at"], name="maps_review_amenity_2022fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "-created_at"], name="maps_review_user_id_737dbc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("amenity", "user")},
        ),
        migrations.AddIndex(
            model_name="amenityphoto",
            index=models.Index(
                fields=["amenity", "-is_primary"], name="maps_amenit_amenity_c501d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenityphoto",
            index=models.Index(
                fields=["review"], name="maps_amenit_review__8e8eef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewvote",
            index=models.Index(
                fields=["review", "value"], name="review_vote_score_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewvote",
            index=models.Index(
                fields=["user", "-updated_at"], name="review_vote_user_updated_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewvote",
            unique_together={("review", "user")},
        ),
    ]
