# Generated by Django 6.0.2 on 2026-02-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
