# Generated by Django 6.0.3 on 2026-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="friday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="friday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="is_open_24hrs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenity",
            name="monday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="monday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="saturday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="saturday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="sunday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="sunday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="thursday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="thursday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="tuesday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="tuesday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="wednesday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="wednesday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="accessibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("Not Accessible", "Not Accessible"),
                    ("Limited Accessibility", "Limited Accessibility"),
                    ("Partially Accessible", "Partially Accessible"),
                    ("Fully Accessible", "Fully Accessible"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["is_open_24hrs"], name="maps_amenit_is_open_494122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["monday_open", "monday_close"],
                name="maps_amenit_monday__21e969_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["tuesday_open", "tuesday_close"],
                name="maps_amenit_tuesday_afd7d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["wednesday_open", "wednesday_close"],
                name="maps_amenit_wednesd_20bdfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["thursday_open", "thursday_close"],
                name="maps_amenit_thursda_bcc3a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["friday_open", "friday_close"],
                name="maps_amenit_friday__7d25a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["saturday_open", "saturday_close"],
                name="maps_amenit_saturda_078037_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["sunday_open", "sunday_close"],
                name="maps_amenit_sunday__e0c0f9_idx",
            ),
        ),
    ]
