# Generated by Django 6.0.2 on 2026-02-25 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_amenity_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenitytype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Amenity Types'},
        ),
        migrations.AddField(
            model_name='amenitytype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_types', to='maps.amenitytype'),
        ),
    ]
