# Generated by Django 6.0.3 on 2026-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_amenity_friday_close_amenity_friday_open_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/%Y/%m/%d/"
            ),
        ),
    ]
