# Generated by Django 6.0.2 on 2026-02-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_amenitytype_options_amenitytype_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='seasonal',
            field=models.BooleanField(default=False),
        ),
    ]
