# Generated by Django 6.0.3 on 2026-03-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_customuser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(1, "Upvote"), (-1, "Downvote")]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="maps.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_votes",
                        to="maps.customuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("review", "user")},
                "indexes": [
                    models.Index(fields=["review", "value"], name="review_vote_score_idx"),
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="review_vote_user_updated_idx",
                    ),
                ],
            },
        ),
    ]
