# Generated by Django 6.0.3 on 2026-03-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_chat_chatparticipant_message"),
        ("maps", "0004_reviewvote"),
    ]

    operations = []
