# Generated by Django 6.0.2 on 2026-02-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_amenity_seasonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='hours_of_operation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
