# Generated by Django 6.0.3 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("maps", "0004_reviewvote")]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="maps.amenity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="maps.customuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "amenity")},
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="fav_user_created_idx",
                    ),
                    models.Index(
                        fields=["amenity", "user"],
                        name="fav_amenity_user_idx",
                    ),
                ],
            },
        ),
    ]
