# Generated by Django 6.0.2 on 2026-02-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_amenity_hours_of_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='position',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='prop_name',
        ),
    ]
