# Generated by Django 6.0.2 on 2026-02-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_remove_amenity_position_remove_amenity_prop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='prop_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
