# Generated by Django 6.0.3 on 2026-04-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_amenityphoto_review"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="amenityphoto",
            index=models.Index(
                fields=["review"], name="maps_amenit_review__8e8eef_idx"
            ),
        ),
    ]
