# Generated by Django 6.0.3 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0008_amenityphoto_maps_amenit_review__8e8eef_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="notify_on_updates",
            field=models.BooleanField(default=True),
        ),
    ]
