# Generated by Django 6.0.3 on 2026-04-07 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0008_amenityphoto_maps_amenit_review__8e8eef_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("session_key", models.CharField(blank=True, max_length=64)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_reports",
                        to="maps.amenity",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
                "indexes": [
                    models.Index(
                        fields=["amenity", "reported_at"], name="avail_amenity_time_idx"
                    ),
                    models.Index(
                        fields=["session_key", "reported_at"],
                        name="avail_session_time_idx",
                    ),
                ],
            },
        ),
    ]
