language: python
python:
  - "3.14"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gdal310
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

install:
  - pip install -r requirements-dev.txt

services:
  - postgresql
addons:
  postgresql: "17"
#  apt:
#    packages:
#      - postgresql-17-postgis-3
before_script:
  # Create the database and enable the GIS extension before Django runs
  - psql -h 127.0.0.1 -p ${PGPORT:-5432} -U postgres -d amenities -c 'create extension postgis;'
  - psql -h 127.0.0.1 -p ${PGPORT:-5432} -U postgres -c 'create database amenities;'

script:
  # --check: doesn't reformat, just exits with error if code isn't "blackened"
  - black --check .
  # Runs the linter using the rules in your .flake8 file
  - flake8 .
  - coverage run -m pytest
  #- pytest --cov=./ --cov-report=xml
  - coverage report  # This prints the table in your Travis log
  - coverage xml     # This creates the file for Codecov

after_script:
  - coveralls --service=travis-pro

deploy:
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nycnow"
    env: "Nycnow-dev"
    bucket_name: "elasticbeanstalk-us-east-2-793314585930"
    #bucket_path: "/"
    zip_file: "django_map.zip"
    on:
      branch: main
      repo: gcivil-nyu-org/team1-mon-spring26

  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nycnow"
    env: "Nycnow-staging"
    bucket_name: "elasticbeanstalk-us-east-2-793314585930"
    #bucket_path: "/"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: gcivil-nyu-org/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nycnow"
    env: "Nycnow-feature"
    bucket_name: "elasticbeanstalk-us-east-2-793314585930"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: ajslezak/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-1"
    app: "nycnow"
    env: "nycnow-env"
    # below needs updating to match your elasticbeanstalk s3 bucket!
    bucket_name: "elasticbeanstalk-us-east-1-004276707923"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: siyajain1/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nyc-now"
    env: "nyc-now-env"
    # below needs updating to match your elasticbeanstalk s3 bucket!
    bucket_name: "elasticbeanstalk-us-east-2-735067023623"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: shichenz1999/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-1"
    app: "django"
    env: "django-env"
    # below needs updating to match your elasticbeanstalk s3 bucket!
    bucket_name: "elasticbeanstalk-us-east-1-853536782152"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: slurpysalmon/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nycnow"
    env: "Nycnow-feature"
    # below needs updating to match your elasticbeanstalk s3 bucket!
    bucket_name: "elasticbeanstalk-us-east-2-557270420035"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: Riddhi3092002/team1-mon-spring26                  

after_success:
  #- bash <(curl -s https://codecov.io/bash)