language: python
python:
  - "3.12"

before_install:
  # 1. Add the official PostgreSQL repository
  - sudo sh -c 'echo "deb http://apt.postgresql.org $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin
  #- sudo service postgresql restart
  #- sleep 1
  #- postgres --version

  # 2. Install Version 17 explicitly
  - sudo apt-get env -y postgresql-17 postgresql-client-17

install:
  - pip install -r requirements-dev.txt

services:
  - postgresql
addons:
  postgresql: "17"
env:
  global:
  - PGPORT=5433
  - PGUSER=postgres
  - PGHOST=localhost
before_script:
  # Create the database and enable the GIS extension before Django runs
  # 1. Create the cluster manually if it doesn't exist
  #- sudo pg_createcluster 17 main --port=$PGPORT --start
  #- sudo pg_lsclusters
  # 1. Create a data directory
  - mkdir -p /tmp/pgdata
  # 2. Initialize the DB (using the full path to version 17)
  - /usr/lib/postgresql/17/bin/initdb -D /tmp/pgdata
  # 3. Start the server on port 5432
  - /usr/lib/postgresql/17/bin/pg_ctl -D /tmp/pgdata -l logfile start
  # 4. Create your database
  - /usr/lib/postgresql/17/bin/psql -c "create database amenities;"
  #- psql -c 'create database amenities;'
  - psql -d amenities -c 'create extension postgis;'
  

script:
  # --check: doesn't reformat, just exits with error if code isn't "blackened"
  - black --check .
  # Runs the linter using the rules in your .flake8 file
  - flake8 .
  - coverage run -m pytest
  #- pytest --cov=./ --cov-report=xml
  - coverage report  # This prints the table in your Travis log
  - coverage xml     # This creates the file for Codecov

after_script:
  - coveralls --service=travis-pro

deploy:
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nycnow"
    env: "Nycnow-dev"
    bucket_name: "elasticbeanstalk-us-east-2-793314585930"
    #bucket_path: "/"
    zip_file: "django_map.zip"
    on:
      branch: main
      repo: gcivil-nyu-org/team1-mon-spring26

  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nycnow"
    env: "Nycnow-staging"
    bucket_name: "elasticbeanstalk-us-east-2-793314585930"
    #bucket_path: "/"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: gcivil-nyu-org/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nycnow"
    env: "Nycnow-feature"
    bucket_name: "elasticbeanstalk-us-east-2-793314585930"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: ajslezak/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-1"
    app: "nycnow"
    env: "nycnow-env"
    # below needs updating to match your elasticbeanstalk s3 bucket!
    bucket_name: "elasticbeanstalk-us-east-1-004276707923"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: siyajain1/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nyc-now"
    env: "nyc-now-env"
    # below needs updating to match your elasticbeanstalk s3 bucket!
    bucket_name: "elasticbeanstalk-us-east-2-735067023623"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: shichenz1999/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-1"
    app: "django"
    env: "django-env"
    # below needs updating to match your elasticbeanstalk s3 bucket!
    bucket_name: "elasticbeanstalk-us-east-1-853536782152"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: slurpysalmon/team1-mon-spring26

  # this is per-user develop deployment
  # (add your repo + my env vars AWS_ACCESS/SECRET_KEY in travis)
  - provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "nycnow"
    env: "Nycnow-feature"
    # below needs updating to match your elasticbeanstalk s3 bucket!
    bucket_name: "elasticbeanstalk-us-east-2-557270420035"
    zip_file: "django_map.zip"
    on:
      branch: develop
      repo: Riddhi3092002/team1-mon-spring26                  

after_success:
  #- bash <(curl -s https://codecov.io/bash)