services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true
    volumes:
      - ..:/workspaces/app:cached
    environment:
      - DB_HOST=db
      - DB_NAME=amenities
      - DB_USER=postgres
      - DB_PASSWORD=postgresF
      - APP_ENV=dev
    network_mode: service:db # Simplifies networking for dev

  db:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amenities
      # This maps the internal Postgres data folder to a persistent volume
    volumes:
      - postgres-data:/var/lib/postgresql/data

# This tells Docker to manage a dedicated space for the data
volumes:
  postgres-data: